function RiskDisclosurePage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-20 text-chalk">
      <h1 className="font-display text-3xl font-semibold">Risk Disclosure</h1>
      <p className="mt-2 text-sm text-chalk-dim">Last updated: August 2026</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-chalk-dim">
        <section>
          <h2 className="font-display text-lg font-semibold text-chalk">Trading Involves Risk</h2>
          <p className="mt-2">
            Trading and investing in financial markets carries substantial risk of loss and
            is not suitable for every individual. You should carefully consider your
            financial situation and risk tolerance before trading. You may lose some or all
            of your invested capital.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-chalk">TradeMind Does Not Predict Markets</h2>
          <p className="mt-2">
            No feature of TradeMind — including analytics, behavior detection, risk
            calculations, the AI coach, or the stock insight signal — predicts future
            prices or guarantees any trading outcome. All figures are historical or
            probabilistic in nature, based on your own past activity or publicly available
            market data, and do not account for future, unforeseen market conditions.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-chalk">Stock Insight Signal</h2>
          <p className="mt-2">
            The Stock Insight feature presents a probability-based estimate derived from
            historical price patterns and recent news sentiment. It is explicitly not a
            prediction of future price movement, and is frequently wrong by design — it
            reflects statistical tendencies in past data, which markets are not obligated
            to repeat. It must never be treated as a signal to buy or sell.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-chalk">Behavioral Flags Are Not Diagnoses</h2>
          <p className="mt-2">
            Behavioral pattern detections (such as possible overtrading or revenge trading)
            are generated by deterministic rules applied to your trade data. They describe
            possible patterns in your recorded activity, not a diagnosis or certain
            statement about your psychological state or intentions.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-chalk">Not a Substitute for Professional Advice</h2>
          <p className="mt-2">
            TradeMind is not a registered investment adviser, broker-dealer, or financial
            institution. Nothing in the Service should be construed as personalized
            financial, investment, tax, or legal advice. Consult a qualified, licensed
            professional before making financial decisions.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-chalk">Your Responsibility</h2>
          <p className="mt-2">
            All trading decisions you make are your own responsibility. TradeMind and its
            operators are not liable for any financial losses resulting from your use of
            the Service.
          </p>
        </section>
      </div>
    </div>
  )
}

export default RiskDisclosurePage