"""create behavior events table

Revision ID: 8351af42597c
Revises: 6656cce7e157
Create Date: 2026-08-21 10:39:14.670523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8351af42597c'
down_revision: Union[str, None] = '6656cce7e157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('trigger_data', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_events_trade_id'), 'behavior_events', ['trade_id'], unique=False)
    op.create_index(op.f('ix_behavior_events_user_id'), 'behavior_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_events_user_id'), table_name='behavior_events')
    op.drop_index(op.f('ix_behavior_events_trade_id'), table_name='behavior_events')
    op.drop_table('behavior_events')
    # ### end Alembic commands ###
