"""add risk settings to users

Revision ID: a8c5f1dfd5aa
Revises: 8351af42597c
Create Date: 2026-08-21 11:03:29.633369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c5f1dfd5aa'
down_revision: Union[str, None] = '8351af42597c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_balance', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('users', sa.Column('max_risk_per_trade_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('users', sa.Column('max_daily_risk_pct', sa.Numeric(precision=5, scale=2), nullable=True))

    op.execute("UPDATE users SET account_balance = 0 WHERE account_balance IS NULL")
    op.execute("UPDATE users SET max_risk_per_trade_pct = 2.0 WHERE max_risk_per_trade_pct IS NULL")
    op.execute("UPDATE users SET max_daily_risk_pct = 6.0 WHERE max_daily_risk_pct IS NULL")

    op.alter_column('users', 'account_balance', nullable=False)
    op.alter_column('users', 'max_risk_per_trade_pct', nullable=False)
    op.alter_column('users', 'max_daily_risk_pct', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_daily_risk_pct')
    op.drop_column('users', 'max_risk_per_trade_pct')
    op.drop_column('users', 'account_balance')
    # ### end Alembic commands ###
