"""add import batches and trade dedupe hash

Revision ID: df7376c389f4
Revises: 37a9859f1224
Create Date: 2026-08-20 17:18:51.910802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df7376c389f4'
down_revision: Union[str, None] = '37a9859f1224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('dedupe_hash', sa.String(length=64), nullable=True))
    op.execute("UPDATE trades SET dedupe_hash = md5(id::text) WHERE dedupe_hash IS NULL")
    op.alter_column('trades', 'dedupe_hash', nullable=False)
    op.create_index(op.f('ix_trades_dedupe_hash'), 'trades', ['dedupe_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_dedupe_hash'), table_name='trades')
    op.drop_column('trades', 'dedupe_hash')
    # ### end Alembic commands ###
